// Cache variables
const NEXT_PUBLIC_STATIC_CACHE_MIN_TTL_DAYS_RAW = Number(process.env.NEXT_PUBLIC_STATIC_CACHE_MIN_TTL_DAYS);
export const NEXT_PUBLIC_STATIC_CACHE_MIN_TTL_DAYS = !isNaN(NEXT_PUBLIC_STATIC_CACHE_MIN_TTL_DAYS_RAW)
  ? NEXT_PUBLIC_STATIC_CACHE_MIN_TTL_DAYS_RAW
  : 180;
export const NEXT_PUBLIC_STATIC_CACHE_MIN_TTL = NEXT_PUBLIC_STATIC_CACHE_MIN_TTL_DAYS * 60 * 60 * 24;
